[package]
name = "migration"
version = "2025.8.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[lints.rust]
unused_imports = "allow"

[dependencies]
async-std = { workspace = true }
sea-orm-migration = { workspace = true }
