[server]
host = "0.0.0.0"
port = 3010

[database]
provider = "sqlite" # "sqlite" or "postgres"

[database.sqlite]
path = "./ofuton.sqlite3"

[database.postgres]
host = "127.0.0.1"
port = 5432
database = "ofuton"
user = "user"
password = "password"

[bucket]
path = "./bucket"
max_upload_size_mb = 10 # MB
request_expiration_seconds = 300 # https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_sigv.html#why-requests-are-signed:~:text=Protect%20against%20potential%20replay%20attacks

[account]
access_key = "please change this field"
secret_key = "please change this field"

[sentry]
dsn = "" # Sentry DSN, leave empty to disable