[package]
name = "ofuton-rs"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["migration"]

[dependencies.tokio]
version = "1.46.0"
features = ["full"]

[dependencies.sea-orm]
version = "1.1.13"
features = ["sqlx-postgres", "sqlx-sqlite", "runtime-tokio-native-tls", "macros"]
