[package]
name = "entity"
version = "2025.8.0"
edition = "2024"
publish = false

[lib]
name = "entity"
path = "src/mod.rs"

[lints.rust]
unused_imports = "allow"

[dependencies]
sea-orm = { workspace = true }
