name: test

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - '!master'
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --no-deps --all-features -- -D warnings

  test:
    runs-on: ${{ matrix.os }}
    needs:
      - check
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Test build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
